CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Models/MyExceptionAttribute.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CZBK.ItcastOA.WebApp.Models
{
    public class MyExceptionAttribute: HandleErrorAttribute
    {
        public static Queue<Exception> ExceptionQueue = new Queue<Exception>();
        /// <summary>
        /// 可以捕获异常数据
        /// </summary>
        /// <param name="filterContext"></param>
        public override void OnException(ExceptionContext filterContext)
        {
            base.OnException(filterContext);
            Exception ex = filterContext.Exception;
            //写到队列
            ExceptionQueue.Enqueue(ex);
            //跳转到错误页面.
            filterContext.HttpContext.Response.Redirect("/Error.html");
        }
    }
}

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CZBK.ItcastOA.WebApp.Controllers
{
    public class BaseController : Controller
    {
        // GET: Base
        /// <summary>
        /// 执行控制器中的方法之前先执行该方法
        /// </summary>
        /// <param name="filterContext"></param>
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            if (Session["userInfo"] == null)
            {
                filterContext.Result = Redirect("/login/Index");
                return;
            }
        }
    }
}

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CZBK.ItcastOA.WebApp.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CZBK.ItcastOA.Common;
using CZBK.ItcastOA.model;

namespace CZBK.ItcastOA.WebApp.Controllers
{
    public class LoginController : Controller
    {
        IBLL.IUserInfoService userInfoService { get; set; }
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        #region 完成用户登录
        public ActionResult UserLogin()
        {
            string validateCode = Session["validateCode"] != null ? Session["validateCode"].ToString() : string.Empty;
            if (string.IsNullOrEmpty(validateCode))
            {
                return Content("no:验证码错误!!");
            }
            Session["validateCode"] = null;
            string txt_Code = Request["vCode"];
            if (!validateCode.Equals(txt_Code, StringComparison.InvariantCultureIgnoreCase))
            {
                return Content("no:验证码错误!!");
            }
            string userName = Request["LoginCode"];
            string userPwd = Request["LoginPwd"];
            var userInfo = userInfoService.LoadEntites(u => u.userName == userName & u.userPwd==userPwd).FirstOrDefault();
            if (userInfo != null)
            {
                Session["userInfo"] = userInfo;
                return Content("ok:登录成功");
            }
            else
            {
                return Content("no:登录失败");
            }
        }

        #endregion

        #region 显示验证码
        public ActionResult ShowValidateCode()
        {
            Common.ValidateCode validateCode = new Common.ValidateCode();
            string code = validateCode.CreateValidateCode(4);
            Session["validateCode"] = code;
            byte[] buffer = validateCode.CreateValidateGraphic(code);//把验证码画在画布上并转为Byte字节
            return File(buffer, "image/jpeg");
        }
        #endregion
    }
}

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Controllers/UserInfoController.cs
using CZBK.ItcastOA.BLL;
using CZBK.ItcastOA.model;
using CZBK.ItcastOA.model.EnumType;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CZBK.ItcastOA.WebApp.Controllers
{
    public class UserInfoController : BaseController
    {
        // GET: UserInfo
        //IBLL.IUserInfoService userInfoService = new UserInfoService();
        IBLL.IUserInfoService userInfoService { get; set; }
        public ActionResult Index()
        {
            return View();
        }

        #region 获取用户列表数据
        public ActionResult GetUserInfoList()
        {
            int pageIndex = Request["page"] != null ? int.Parse(Request["page"]) : 1;
            int pageSize = Request["rows"] != null ? int.Parse(Request["rows"]) : 1;
            int totalCount;
            short delFlag = (short)DeleteEnumType.DelFlag.Normal;
            var userInfoList = userInfoService.LoadPageEntities<string>(pageIndex, pageSize, out totalCount, c => c.delFlag == delFlag, c => c.id, true);
            var temp = from u in userInfoList
                       select new
                       {
                           id = u.id,
                           UName = u.userName,
                           UEmail = u.Email,
                           ULogin = u.LoginDate
                       };
            return Json(new { rows = temp, total = totalCount });
        }
        #endregion

        #region 删除用户数据
        public ActionResult DeleteUserInfo()
        {
            string strId = Request["strId"];
            string[] strIds = strId.Split(',');
            List<string> list = new List<string>();
            foreach (var id in strIds)
            {
                list.Add(id);
            }
            if (userInfoService.DeleteEntities(list))
            {
                return Content("OK");
            }
            else
            {
                return Content("Fail");
            }
        }
        #endregion

        #region 添加用户数据
        public ActionResult AdduserInfo(UserInfo userInfo)
        {
            userInfo.delFlag = 0;
            userInfoService.AddEntity(userInfo);
            return Content("OK");
        }

        #endregion

        #region 展示需要修改的用户数据
        public ActionResult ShowEditUserInfo()
        {
            var id = Request["id"];
            var userInfo = userInfoService.LoadEntites(u=>u.id==id).FirstOrDefault();
            return Json(userInfo, JsonRequestBehavior.AllowGet);
        }

        #endregion


        #region 编辑用户数据

        public ActionResult EditUserInfo()
        {
            var id = Request["id"];
            var userInfo = userInfoService.LoadEntites(u => u.id == id).FirstOrDefault();
            if (userInfo != null)
            {
                userInfo.id = id;
                userInfo.userName = Request["userName"];
                userInfo.Email = Request["Email"];
                userInfoService.EditEntity(userInfo);
                return Content("OK");
            }
            else
            {
                return Content("Fail");
            }
        }

        #endregion
    }
}

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Views/Login/index.cshtml
@{
    ViewBag.Title = "index";
}
<!DOCTYPE html>
<html>
<head>
    <title>OA后台管理系统登录</title>
    <script type="text/javascript">
        if (window.parent.window != window) {
            window.top.location.href = "/Home/CheckLogin";
        }
    </script>
    <script src="../../Scripts/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="../../Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        function changeCheckCode() {
            $("#img").attr("src", $("#img").attr("src") + 1);
        }
        function afterLogin(data) {
            var serverData = data.split(':');
            if (serverData[0] == "ok") {
                window.location.href="/Home/Index"
            } else {
                $("#errorMsg").css("display", "block");
                $("#errorMsg").text(serverData[1]);
                changeCheckCode();
            }
        }
    </script>
    <style type="text/css">
        * {
            padding: 0;
            margin: 0;
        }

        body {
            text-align: center;
            background: #4974A4;
        }

        #login {
            width: 740px;
            margin: 0 auto;
            font-size: 12px;
        }

        #loginlogo {
            width: 700px;
            height: 100px;
            overflow: hidden;
            background: url('/Content/Images/login/logo.png') no-repeat;
            margin-top: 50px;
        }

        #loginpanel {
            width: 729px;
            position: relative;
            height: 320px;
        }

        .panel-h {
            width: 729px;
            height: 20px;
            background: url('/Content/Images/login/panel-h.gif') no-repeat;
            position: absolute;
            top: 0px;
            left: 0px;
            z-index: 3;
        }

        .panel-f {
            width: 729px;
            height: 13px;
            background: url('/Content/Images/login/panel-f.gif') no-repeat;
            position: absolute;
            bottom: 0px;
            left: 0px;
            z-index: 3;
        }

        .panel-c {
            z-index: 2;
            background: url('/Content/Images/login/panel-c.gif') repeat-y;
            width: 729px;
            height: 310px;
        }

        .panel-c-l {
            position: absolute;
            left: 60px;
            top: 40px;
        }

        .panel-c-r {
            position: absolute;
            right: 20px;
            top: 50px;
            width: 222px;
            line-height: 200%;
            text-align: left;
        }

        .panel-c-l h3 {
            color: #556A85;
            margin-bottom: 10px;
        }

        .panel-c-l td {
            padding: 7px;
        }

        .login-text {
            height: 24px;
            left: 24px;
            border: 1px solid #e9e9e9;
            background: #f9f9f9;
        }

        .login-text-focus {
            border: 1px solid #E6BF73;
        }

        .login-btn {
            width: 114px;
            height: 29px;
            color: #E9FFFF;
            line-height: 29px;
            background: url('/Content/Images/login/login-btn.gif') no-repeat;
            border: none;
            overflow: hidden;
            cursor: pointer;
        }

        #txtUsername, #code, #txtPassword {
            width: 191px;
        }

        #logincopyright {
            text-align: center;
            color: White;
            margin-top: 50px;
        }

        a {
            color: Black;
        }

            a:hover {
                color: Red;
                text-decoration: underline;
            }
    </style>


</head>
<body style="padding: 10px">

    <div id="login">
        <div id="loginlogo">
        </div>
        <div id="loginpanel">
            <div class="panel-h">
            </div>
            <div class="panel-c">
                <div class="panel-c-l">
                    @using (Ajax.BeginForm("UserLogin", "Login", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterLogin", LoadingElementId = "div1" }, new { id = "loginForm" }))
                    {
                        <table cellpadding="0" cellspacing="0">
                            <tbody>
                                <tr>
                                    <td align="left" colspan="2">
                                        <h3>
                                            请使用ItcastOA管理系统账号登录
                                        </h3>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="right">
                                        账号：
                                    </td>
                                    <td align="left">
                                        <input type="text" name="LoginCode" id="LoginCode" class="login-text" />

                                    </td>
                                </tr>
                                <tr>
                                    <td align="right">
                                        密码：
                                    </td>
                                    <td align="left">
                                        <input type="password" name="LoginPwd" id="LoginPwd" value="" class="login-text" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        验证码：
                                    </td>
                                    <td align="left">
                                        <input type="text" class="login-text" id="code" name="vCode" value="" />
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                    </td>
                                    <td>
                                        <img id="img" src="/Login/ShowValidateCode?id=1" style="float: left; height: 24px;" />
                                        <div style="float: left; margin-left: 5px; margin-top: 10px;">
                                            <a href="javascript:void(0)" onclick="changeCheckCode();return false;">看不清，换一张</a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" colspan="2">
                                         <input type="submit" id="btnLogin" value="登录" class="login-btn" /><span id="errorMsg" style="font-size:14px;color:red;display:none"></span>
                                        <div id="div1" style="display:none">正在登录，请稍后....</div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    }
                </div>
                <div class="panel-c-r">
                    <p>
                        请从左侧输入登录账号和密码登录
                    </p>
                    <p>
                        如果遇到系统问题，请联系网络管理员。
                    </p>
                    <p>
                        如果没有账号，请联系网站管理员。
                    </p>
                    <p>
                        联系电话:8849
                    </p>
                </div>
            </div>
            <div class="panel-f">
            </div>
        </div>
        <div id="logincopyright">
            Copyright ? 2020 itcast.com
        </div>
    </div>
</body>
</html>

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CZBK.ItcastOA/CZBK.ItcastOA.WebApp/Views/UserInfo/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Index</title>
    <link href="~/Content/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/datapattern.js"></script>
    <script type="text/javascript">
        $(function () {
            loadData();
            $('#dlg_Add').dialog('close');
            $('#dlg_Edit').dialog('close');
            $("#addDiv").css("display", "none");
            $("#editDiv").css("display", "none");
        });

        //表格数据读取
        function loadData(pars) {
            $('#tt').datagrid({
                url: '/UserInfo/GetUserInfoList',
                title: '用户数据表格',
                width: 700,
                height: 400,
                fitColumns: true, //列自适应
                nowrap: false,
                idField: 'ID',//主键列的列明
                loadMsg: '正在加载用户的信息...',
                pagination: true,//是否有分页
                singleSelect: false,//是否单行选择
                pageSize: 5,//页大小，一页多少条数据
                pageNumber: 1,//当前页，默认的
                pageList: [5, 10, 15, 20],
                queryParams: pars,//往后台传递参数
                columns: [[//c.UserName, c.UserPass, c.Email, c.RegTime
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
                    { field: 'id', title: '工号', width: 120 },
                    { field: 'UName', title: '姓名', width: 120 },
                    { field: 'UEmail', title: '邮箱', width: 120 },
                    //{
                    //    field: 'ULogin', title: '上次登录时间', width: 80, align: 'right',
                    //    formatter: function (value, row, index) {
                    //        return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-MM-dd");
                    //    }
                    //}
                ]],
                toolbar: [{
                    id: 'btnDelete',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: function () {

                        deleteInfo();
                    }
                }, {
                    id: 'btnAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {

                        addInfo();
                    }
                }, {
                    id: 'btnEidt',
                    text: '编辑',
                    iconCls: 'icon-edit',
                    handler: function () {

                        showEditInfo();
                    }
                }, {
                    id: 'btnSetUserRole',
                    text: '为用户分配角色',
                    iconCls: 'icon-edit',
                    handler: function () {

                        showSetUserRoleInfo();
                    }
                }, {
                    id: 'btnSetUserAction',
                    text: '为用户分配权限',
                    iconCls: 'icon-edit',
                    handler: function () {

                        showSetUserActionInfo();
                    }
                }],
            });
        }


        //删除数据
        function deleteInfo() {
            var rows = $('#tt').datagrid("getSelections");
            if (!rows || rows.length == 0) {
                $.messager.alert("提醒", "请选择需要删除的记录", "error");
                return;
            }
            $.messager.confirm("提示", "确定要删除数据吗?", function (r) {
                if (r) {
                    //获取要删除的记录的ID值
                    var rowsLength = rows.length;
                    var strId = "";
                    for (var i = 0; i < rowsLength; i++) {
                        strId = strId + rows[i].UName + ",";
                    }
                    strId = strId.substring(0, strId.length - 1);
                    //将需要删除的记录发送到服务器端
                    $.post("/UserInfo/DeleteUserInfo", { "strId": strId }, function (data) {
                        if (data == "OK") {
                            $('#tt').datagrid('reload');//加载表格不会跳到第一页
                            //清除上次所选择的项的值(ajax异步请求部分刷新,需要手动函数进行清楚控件内的属性或选择项)
                            $('#tt').datagrid('clearSelections');
                        }
                        else {
                            $.messager.alert("提醒", "删除记录失败!", "error");
                        }
                    })
                }
            }
            )
        };

        //添加数据
        function addInfo() {
            $('#dlg_Add').dialog('open');
            $('#addDiv').css('display', 'block');
        }

        //表单校验
        function validateInfo(control) {
            control.validate({//表示对哪个form表单进行校验，获取form标签的id属性的值
                rules: {//表示验证规则
                    ID: "required",//表示对哪个表单元素进行校验，要写具体的表单元素的name属性的值
                    userName: {
                        required: true
                    },
                    Email: {
                        required: true,
                        //minlength: 5
                    }
                },
                messages: {
                    ID: "请输入工号",
                    userName: {
                        required: "请输入用户名"
                    },
                    Email: {
                        required: "请输入邮箱",
                    }
                }
            });
        }

        //编辑数据
        function showEditInfo() {
            var rows = $('#tt').datagrid("getSelections");
            if (rows.length == 0) {
                $.messager.alert("提示", "请选择要修改的数据", "error");
                return;
            }
            if (rows.length > 1) {
                $.messager.alert("提示", "请选择一条修改的数据", "error");
                return;
            }
            var id = rows[0].id;
            $.post("/UserInfo/ShowEditUserInfo", { "id": id }, function (data) {
                $('#txt_id').val(data.id);
                $('#txt_userName').val(data.userName);
                $('#txt_Email').val(data.Email);
                $('#txt_Remark').val(data.Remark);
            });
            $('#dlg_Edit').dialog('open');
            $('#editDiv').css('display', 'block');
        };

        //完成添加数据后调用的方法
        function afterAdd(data) {
            if (data == "OK") {
                $('#dlg_Add').dialog('close');
                $('#tt').datagrid('reload');//加载表格不会跳到第一页
            }
            else {
                $.messager.alert("提醒", "添加数据失败!", "Fail");
            }
        }

        //完成编辑数据后调用的方法
        function afterEdit(data) {
            if (data == "OK") {
                $('#dlg_Edit').dialog('close');
                $('#tt').datagrid('reload');//加载表格不会跳到第一页
                $('#tt').datagrid('clearSelections');
            }
            else {
                $.messager.alert("提醒", "编辑数据失败!", "Fail");
            }
        }
    </script>
</head>
<body>
    @* --------------------------------------------------搜索表格-------------------------------------------- *@
    <div>
        <table id="tt" style="width: 700px;" title="标题，可以使用代码进行初始化，也可以使用这种属性的方式" iconcls="icon-edit">
        </table>
    </div>
    @* --------------------------------------------------新增表单-------------------------------------------- *@
    <div id="dlg_Add" class="easyui-dialog" title="新增用户信息" style="width:400px;height:300px;padding:10px"
         data-options="
				iconCls: 'icon-save',
				buttons: [{
					text:'Ok',
					iconCls:'icon-ok',
					handler:function(){
						 validateInfo($('#addForm'));
						$('#addForm').submit();
					}
				},{
					text:'Cancel',
					handler:function(){
				        $('#dlg_Add').dialog('close');
					}
				}]
			">
        <div id="addDiv" style="display:none">
            @using (Ajax.BeginForm("AddUserInfo", "UserInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAdd" }, new { id = "addForm" }))
            {
                <input type="hidden" name="Remark" id="txt_Remark" />
                <table>
                    <tr><td>用户ID</td><td><input type="text" name="ID" /></td></tr>
                    <tr><td>用户名</td><td><input type="text" name="userName" /></td></tr>
                    <tr><td>邮箱地址</td><td><input type="text" name="Email" /></td></tr>
                </table>
            }
        </div>
    </div>


    @* --------------------------------------------------编辑表单-------------------------------------------- *@
    <div id="dlg_Edit" class="easyui-dialog" title="编辑用户信息" style="width:400px;height:300px;padding:10px"
         data-options="
				iconCls: 'icon-save',
				buttons: [{
					text:'Ok',
					iconCls:'icon-ok',
					handler:function(){
						$('#editForm').submit();
					}
				},{
					text:'Cancel',
					handler:function(){
					    $('#dlg_Edit').dialog('close');
					}
				}]
			">
        <div id="editDiv" style="display:none">
            @using (Ajax.BeginForm("EditUserInfo", "UserInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterEdit" }, new { id = "editForm" }))
            {
                <table>
                    <tr><td>用户ID</td><td><input type="text" name="ID" id="txt_id" readonly="readonly" style="background-color:lightgray" /></td></tr>
                    <tr><td>用户名</td><td><input type="text" name="userName" id="txt_userName" /></td></tr>
                    <tr><td>邮箱地址</td><td><input type="text" name="Email" id="txt_Email" /></td></tr>
                </table>
            }
        </div>
    </div>
</body>

</html>